name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run basic tests
        run: |
          python -c "import streamlit; print('Streamlit version:', streamlit.__version__)"
          python -c "import yfinance as yf; print('yfinance version:', yf.__version__)"
          
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy to Streamlit
        run: |
          echo "Deployment would happen here"
          echo "For Streamlit Cloud, connect your GitHub repo at https://share.streamlit.io"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
