name: Deploy to Streamlit

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run Streamlit app
        run: |
          echo "Starting Streamlit..."
          streamlit run app.py --server.port ${{ env.PORT }} &
          sleep 5
          curl --retry 5 --retry-delay 3 --retry-max-time 30 --connect-timeout 20 http://localhost:${{ env.PORT }}
        env:
          PORT: 8501
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
